### ISSUE TITLE
input depthmap format

### ISSUE THREAD

**Issue by jin20200930** [VCL3D/StructureNet#3]
I ran inference.py with your pretrained model, but output files are black images. I tested with depthmap images from azure kinect as input file for an inference step. And I also tested with imported depthmap images from an asymmetric_box.obj using blender.
I wonder if there is any specific format or condition for input depthmap files.
- specific pixel size ( 8bit, 16bit, 24bit, ... )
- specific resolution ( 320x160, ... )
- image captured from specific angle or distance
If there is specific condition for testing, could you please explain it?
or If it is possible, could you provides the sample depthmap images for testing?

**Comment by vladsterz** [comment]
Hello @jin20200930 ,
Inputs to our network must be of __.pgm__ format and the data values should be in __meters__. So if your depth map is written in millimeters, you have to set argument __scale__ to __0.001__, so that __depth_map__ * __scale__ is __meters__. Other that that, input must be at constant shape of (320 x 180). Here is a sample input:
![image](https://user-images.githubusercontent.com/17708197/94811931-b3ea8600-03fe-11eb-81b6-ae6b37d2294b.png)

**Comment by Xilocient** [comment]
Hello,Why is the output of the picture I used for you still black？

**Comment by vladsterz** [comment]
An exemplary sample has been uploaded under [example](./example). Note that the input must be in __.pgm__ format and _--scale_ argument for this example must be set to `0,001` in order to convert in to meters, because _input.pgm_ stores distances in millimeters.
